// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddFavorite(arg1:domain.Track):Promise<void>;

export function CloseApp():Promise<void>;

export function ExportLyrics(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAppIcon():Promise<string>;

export function GetByID(arg1:number):Promise<domain.Track>;

export function GetCloseToTray():Promise<boolean>;

export function GetDiscordPresence():Promise<boolean>;

export function GetFavorites():Promise<Array<domain.Track>>;

export function GetFavoritesDir():Promise<string>;

export function GetVersion():Promise<string>;

export function IsFavorite(arg1:number):Promise<boolean>;

export function PickFavoritesDir():Promise<string>;

export function RemoveFavorite(arg1:number):Promise<void>;

export function Search(arg1:string):Promise<Array<domain.Track>>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetDiscordPresence(arg1:boolean):Promise<void>;

export function UpdatePresenceIdle():Promise<void>;

export function UpdatePresenceSearching(arg1:string):Promise<void>;

export function UpdatePresenceTrack(arg1:string,arg2:string,arg3:boolean):Promise<void>;
