// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ConnectGoogleDrive() {
  return window['go']['main']['App']['ConnectGoogleDrive']();
}

export function ConnectSpotify() {
  return window['go']['main']['App']['ConnectSpotify']();
}

export function DeleteCustomTheme(arg1) {
  return window['go']['main']['App']['DeleteCustomTheme'](arg1);
}

export function DisconnectGoogleDrive() {
  return window['go']['main']['App']['DisconnectGoogleDrive']();
}

export function DisconnectSpotify() {
  return window['go']['main']['App']['DisconnectSpotify']();
}

export function DownloadAndInstall() {
  return window['go']['main']['App']['DownloadAndInstall']();
}

export function ExportLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLyrics'](arg1, arg2, arg3);
}

export function ExportTheme(arg1) {
  return window['go']['main']['App']['ExportTheme'](arg1);
}

export function GetAppIcon() {
  return window['go']['main']['App']['GetAppIcon']();
}

export function GetAutoUpdateEnabled() {
  return window['go']['main']['App']['GetAutoUpdateEnabled']();
}

export function GetByID(arg1) {
  return window['go']['main']['App']['GetByID'](arg1);
}

export function GetCheckUpdatesEnabled() {
  return window['go']['main']['App']['GetCheckUpdatesEnabled']();
}

export function GetCloseToTray() {
  return window['go']['main']['App']['GetCloseToTray']();
}

export function GetCurrentTheme() {
  return window['go']['main']['App']['GetCurrentTheme']();
}

export function GetCustomThemes() {
  return window['go']['main']['App']['GetCustomThemes']();
}

export function GetDiscordPresence() {
  return window['go']['main']['App']['GetDiscordPresence']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFavoritesDir() {
  return window['go']['main']['App']['GetFavoritesDir']();
}

export function GetGoogleDriveEnabled() {
  return window['go']['main']['App']['GetGoogleDriveEnabled']();
}

export function GetLastSyncTime() {
  return window['go']['main']['App']['GetLastSyncTime']();
}

export function GetSpotifyAutoSearch() {
  return window['go']['main']['App']['GetSpotifyAutoSearch']();
}

export function GetSpotifyEnabled() {
  return window['go']['main']['App']['GetSpotifyEnabled']();
}

export function GetUpdateAvailable() {
  return window['go']['main']['App']['GetUpdateAvailable']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportTheme() {
  return window['go']['main']['App']['ImportTheme']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function PickFavoritesDir() {
  return window['go']['main']['App']['PickFavoritesDir']();
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function SaveCustomTheme(arg1) {
  return window['go']['main']['App']['SaveCustomTheme'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetAutoUpdateEnabled(arg1) {
  return window['go']['main']['App']['SetAutoUpdateEnabled'](arg1);
}

export function SetCheckUpdatesEnabled(arg1) {
  return window['go']['main']['App']['SetCheckUpdatesEnabled'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetCurrentTheme(arg1) {
  return window['go']['main']['App']['SetCurrentTheme'](arg1);
}

export function SetDiscordPresence(arg1) {
  return window['go']['main']['App']['SetDiscordPresence'](arg1);
}

export function SetSpotifyAutoSearch(arg1) {
  return window['go']['main']['App']['SetSpotifyAutoSearch'](arg1);
}

export function SetSpotifyEnabled(arg1) {
  return window['go']['main']['App']['SetSpotifyEnabled'](arg1);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['App']['SkipUpdateVersion'](arg1);
}

export function SyncFromGoogleDrive() {
  return window['go']['main']['App']['SyncFromGoogleDrive']();
}

export function SyncToGoogleDrive() {
  return window['go']['main']['App']['SyncToGoogleDrive']();
}

export function UpdatePresenceIdle() {
  return window['go']['main']['App']['UpdatePresenceIdle']();
}

export function UpdatePresenceSearching(arg1) {
  return window['go']['main']['App']['UpdatePresenceSearching'](arg1);
}

export function UpdatePresenceTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePresenceTrack'](arg1, arg2, arg3);
}
