// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function ExportLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLyrics'](arg1, arg2, arg3);
}

export function GetByID(arg1) {
  return window['go']['main']['App']['GetByID'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFavoritesDir() {
  return window['go']['main']['App']['GetFavoritesDir']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function PickFavoritesDir() {
  return window['go']['main']['App']['PickFavoritesDir']();
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
