// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ExportLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLyrics'](arg1, arg2, arg3);
}

export function GetAppIcon() {
  return window['go']['main']['App']['GetAppIcon']();
}

export function GetByID(arg1) {
  return window['go']['main']['App']['GetByID'](arg1);
}

export function GetCloseToTray() {
  return window['go']['main']['App']['GetCloseToTray']();
}

export function GetDiscordPresence() {
  return window['go']['main']['App']['GetDiscordPresence']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFavoritesDir() {
  return window['go']['main']['App']['GetFavoritesDir']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function PickFavoritesDir() {
  return window['go']['main']['App']['PickFavoritesDir']();
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetDiscordPresence(arg1) {
  return window['go']['main']['App']['SetDiscordPresence'](arg1);
}

export function UpdatePresenceIdle() {
  return window['go']['main']['App']['UpdatePresenceIdle']();
}

export function UpdatePresenceSearching(arg1) {
  return window['go']['main']['App']['UpdatePresenceSearching'](arg1);
}

export function UpdatePresenceTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePresenceTrack'](arg1, arg2, arg3);
}
